more_topics_button_text:
  type: string
  default: "Show more activity"
  description: "Text displayed on More button"
post_button_text:
  type: string
  default: ""
  description: "Text displayed on Post button"
showcase_title_text:
  type: string
  default: "Recent Discussions"
  description: "Text displayed on showcase title"
feed_list:
  placeholder: "Title, List length, Filter, Tag, Category id, Link, solved"
  client: true
  default: "Latest Topics, 6, latest, , , /latest,"
  type: list
  description: |
    Each line should be in the format of <code>Feed title</code>, <code>List length</code>, <code>List filter</code>, <code>Tag filter</code>, <code>Category filter</code>, <code>Feed link</code>, <code>Solved(true/false)</code>.
plugin_outlet:
  type: enum
  default: "above-main-container"
  choices:
    - "above-main-container"
    - "below-site-header"
    - "discovery-list-container-top"
  description: "Advanced layout setting"
category_filter:
  type: list
  list_type: category
  default: ""
  description: "Choose which categories are being shown."
